baseURL = 'https://blog.nandabhat.com/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Nanda Bhat'
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

theme = 'hyde'
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/n89nanda/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/nanda-b-949a9225/"}
  ]

[params]
  description = "Personal blog"
  themeColor = "theme-base-0f"
  Description = "My Personal blog about all things software"

googleAnalytics = 'G-XJY3VMPK36'

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5